// This file is auto-generated by @hey-api/openapi-ts

import {
  type Options as ClientOptions,
  type TDataShape,
  type Client,
  urlSearchParamsBodySerializer,
} from "./client";
import type {
  LoginLoginAccessTokenData,
  LoginLoginAccessTokenResponses,
  LoginLoginAccessTokenErrors,
  LoginTestTokenData,
  LoginTestTokenResponses,
  LoginLoginJsonData,
  LoginLoginJsonResponses,
  LoginLoginJsonErrors,
  LoginChangePasswordData,
  LoginChangePasswordResponses,
  LoginChangePasswordErrors,
  HealthHealthData,
  HealthHealthResponses,
  UsersListUsersData,
  UsersListUsersResponses,
  UsersCreateUserData,
  UsersCreateUserResponses,
  UsersCreateUserErrors,
  UsersDeleteUserData,
  UsersDeleteUserResponses,
  UsersDeleteUserErrors,
  UsersUpdateUserData,
  UsersUpdateUserResponses,
  UsersUpdateUserErrors,
  UsersResetUserPasswordData,
  UsersResetUserPasswordResponses,
  UsersResetUserPasswordErrors,
  ConfigReadAppConfigData,
  ConfigReadAppConfigResponses,
  ConfigUpdateAppConfigData,
  ConfigUpdateAppConfigResponses,
  ConfigUpdateAppConfigErrors,
  ArchiveTasksListArchiveTasksData,
  ArchiveTasksListArchiveTasksResponses,
  ArchiveTasksListArchiveTasksErrors,
  ArchiveTasksCreateArchiveTaskData,
  ArchiveTasksCreateArchiveTaskResponses,
  ArchiveTasksCreateArchiveTaskErrors,
  ArchiveTasksListArchiveTagsData,
  ArchiveTasksListArchiveTagsResponses,
  ArchiveTasksDeleteArchiveTaskData,
  ArchiveTasksDeleteArchiveTaskResponses,
  ArchiveTasksDeleteArchiveTaskErrors,
  ArchiveTasksReadArchiveTaskData,
  ArchiveTasksReadArchiveTaskResponses,
  ArchiveTasksReadArchiveTaskErrors,
  ArchiveTasksUpdateArchiveTaskData,
  ArchiveTasksUpdateArchiveTaskResponses,
  ArchiveTasksUpdateArchiveTaskErrors,
  ArchiveTasksListArchiveTaskFilesData,
  ArchiveTasksListArchiveTaskFilesResponses,
  ArchiveTasksListArchiveTaskFilesErrors,
  ArchiveTasksUploadArchiveTaskFileData,
  ArchiveTasksUploadArchiveTaskFileResponses,
  ArchiveTasksUploadArchiveTaskFileErrors,
  ArchiveTasksDeleteArchiveTaskFileData,
  ArchiveTasksDeleteArchiveTaskFileResponses,
  ArchiveTasksDeleteArchiveTaskFileErrors,
  ArchiveTasksUpdateArchiveTaskFileData,
  ArchiveTasksUpdateArchiveTaskFileResponses,
  ArchiveTasksUpdateArchiveTaskFileErrors,
  ArchiveTasksMarkArchiveTaskReadData,
  ArchiveTasksMarkArchiveTaskReadResponses,
  ArchiveTasksMarkArchiveTaskReadErrors,
  ArchiveTasksRearchiveTaskData,
  ArchiveTasksRearchiveTaskResponses,
  ArchiveTasksRearchiveTaskErrors,
  ArchiveTasksResumeManualActionData,
  ArchiveTasksResumeManualActionResponses,
  ArchiveTasksResumeManualActionErrors,
  ArchiveTasksContinueArchiveVideoData,
  ArchiveTasksContinueArchiveVideoResponses,
  ArchiveTasksContinueArchiveVideoErrors,
  ArchiveTasksOpenArchiveTaskInBrowserData,
  ArchiveTasksOpenArchiveTaskInBrowserResponses,
  ArchiveTasksOpenArchiveTaskInBrowserErrors,
  ArchiveTasksOpenManualActionInBrowserData,
  ArchiveTasksOpenManualActionInBrowserResponses,
  ArchiveTasksOpenManualActionInBrowserErrors,
  ArchiveTasksDownloadArchiveResultData,
  ArchiveTasksDownloadArchiveResultResponses,
  ArchiveTasksDownloadArchiveResultErrors,
  ArchiveTasksViewArchiveResultData,
  ArchiveTasksViewArchiveResultResponses,
  ArchiveTasksViewArchiveResultErrors,
  ArchiveTasksDownloadVideoResultData,
  ArchiveTasksDownloadVideoResultResponses,
  ArchiveTasksDownloadVideoResultErrors,
  RssFeedsListRssFeedsData,
  RssFeedsListRssFeedsResponses,
  RssFeedsCreateRssFeedData,
  RssFeedsCreateRssFeedResponses,
  RssFeedsCreateRssFeedErrors,
  RssFeedsDeleteRssFeedData,
  RssFeedsDeleteRssFeedResponses,
  RssFeedsDeleteRssFeedErrors,
  RssFeedsUpdateRssFeedData,
  RssFeedsUpdateRssFeedResponses,
  RssFeedsUpdateRssFeedErrors,
  RssFeedsRefreshRssFeedData,
  RssFeedsRefreshRssFeedResponses,
  RssFeedsRefreshRssFeedErrors,
  AuthLogoutData,
  AuthLogoutResponses,
  AuthReadCurrentUserData,
  AuthReadCurrentUserResponses,
} from "./types.gen";
import { client as _heyApiClient } from "./client.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Login Access Token
 */
export const loginLoginAccessToken = <ThrowOnError extends boolean = false>(
  options: Options<LoginLoginAccessTokenData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    LoginLoginAccessTokenResponses,
    LoginLoginAccessTokenErrors,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    url: "/api/v1/login/access-token",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });
};

/**
 * Test Token
 */
export const loginTestToken = <ThrowOnError extends boolean = false>(
  options?: Options<LoginTestTokenData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).post<
    LoginTestTokenResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/login/test-token",
    ...options,
  });
};

/**
 * Login Json
 */
export const loginLoginJson = <ThrowOnError extends boolean = false>(
  options: Options<LoginLoginJsonData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    LoginLoginJsonResponses,
    LoginLoginJsonErrors,
    ThrowOnError
  >({
    url: "/api/v1/auth/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Change Password
 */
export const loginChangePassword = <ThrowOnError extends boolean = false>(
  options: Options<LoginChangePasswordData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    LoginChangePasswordResponses,
    LoginChangePasswordErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/change-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Health
 */
export const healthHealth = <ThrowOnError extends boolean = false>(
  options?: Options<HealthHealthData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    HealthHealthResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/v1/health",
    ...options,
  });
};

/**
 * List Users
 */
export const usersListUsers = <ThrowOnError extends boolean = false>(
  options?: Options<UsersListUsersData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    UsersListUsersResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/users",
    ...options,
  });
};

/**
 * Create User
 */
export const usersCreateUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersCreateUserData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    UsersCreateUserResponses,
    UsersCreateUserErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/users",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete User
 */
export const usersDeleteUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersDeleteUserData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    UsersDeleteUserResponses,
    UsersDeleteUserErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/users/{user_id}",
    ...options,
  });
};

/**
 * Update User
 */
export const usersUpdateUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersUpdateUserData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    UsersUpdateUserResponses,
    UsersUpdateUserErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/users/{user_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Reset User Password
 */
export const usersResetUserPassword = <ThrowOnError extends boolean = false>(
  options: Options<UsersResetUserPasswordData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    UsersResetUserPasswordResponses,
    UsersResetUserPasswordErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/users/{user_id}/reset-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Read App Config
 */
export const configReadAppConfig = <ThrowOnError extends boolean = false>(
  options?: Options<ConfigReadAppConfigData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ConfigReadAppConfigResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/app-config",
    ...options,
  });
};

/**
 * Update App Config
 */
export const configUpdateAppConfig = <ThrowOnError extends boolean = false>(
  options: Options<ConfigUpdateAppConfigData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    ConfigUpdateAppConfigResponses,
    ConfigUpdateAppConfigErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/app-config",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List Archive Tasks
 */
export const archiveTasksListArchiveTasks = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ArchiveTasksListArchiveTasksData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ArchiveTasksListArchiveTasksResponses,
    ArchiveTasksListArchiveTasksErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/archive-tasks",
    ...options,
  });
};

/**
 * Create Archive Task
 */
export const archiveTasksCreateArchiveTask = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ArchiveTasksCreateArchiveTaskData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    ArchiveTasksCreateArchiveTaskResponses,
    ArchiveTasksCreateArchiveTaskErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/archive-tasks",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List Archive Tags
 */
export const archiveTasksListArchiveTags = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ArchiveTasksListArchiveTagsData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ArchiveTasksListArchiveTagsResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/archive-tags",
    ...options,
  });
};

/**
 * Delete Archive Task
 */
export const archiveTasksDeleteArchiveTask = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ArchiveTasksDeleteArchiveTaskData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    ArchiveTasksDeleteArchiveTaskResponses,
    ArchiveTasksDeleteArchiveTaskErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/archive-tasks/{task_id}",
    ...options,
  });
};

/**
 * Read Archive Task
 */
export const archiveTasksReadArchiveTask = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ArchiveTasksReadArchiveTaskData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ArchiveTasksReadArchiveTaskResponses,
    ArchiveTasksReadArchiveTaskErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/archive-tasks/{task_id}",
    ...options,
  });
};

/**
 * Update Archive Task
 */
export const archiveTasksUpdateArchiveTask = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ArchiveTasksUpdateArchiveTaskData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    ArchiveTasksUpdateArchiveTaskResponses,
    ArchiveTasksUpdateArchiveTaskErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/archive-tasks/{task_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List Archive Task Files
 */
export const archiveTasksListArchiveTaskFiles = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ArchiveTasksListArchiveTaskFilesData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ArchiveTasksListArchiveTaskFilesResponses,
    ArchiveTasksListArchiveTaskFilesErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/archive-tasks/{task_id}/file-list",
    ...options,
  });
};

/**
 * Upload Archive Task File
 */
export const archiveTasksUploadArchiveTaskFile = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ArchiveTasksUploadArchiveTaskFileData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    ArchiveTasksUploadArchiveTaskFileResponses,
    ArchiveTasksUploadArchiveTaskFileErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/archive-tasks/{task_id}/files",
    ...options,
  });
};

/**
 * Delete Archive Task File
 */
export const archiveTasksDeleteArchiveTaskFile = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ArchiveTasksDeleteArchiveTaskFileData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    ArchiveTasksDeleteArchiveTaskFileResponses,
    ArchiveTasksDeleteArchiveTaskFileErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/archive-tasks/{task_id}/files/{file_name}",
    ...options,
  });
};

/**
 * Update Archive Task File
 */
export const archiveTasksUpdateArchiveTaskFile = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ArchiveTasksUpdateArchiveTaskFileData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    ArchiveTasksUpdateArchiveTaskFileResponses,
    ArchiveTasksUpdateArchiveTaskFileErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/archive-tasks/{task_id}/files/{file_name}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Mark Archive Task Read
 */
export const archiveTasksMarkArchiveTaskRead = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ArchiveTasksMarkArchiveTaskReadData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    ArchiveTasksMarkArchiveTaskReadResponses,
    ArchiveTasksMarkArchiveTaskReadErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/archive-tasks/{task_id}/mark-read",
    ...options,
  });
};

/**
 * Rearchive Task
 */
export const archiveTasksRearchiveTask = <ThrowOnError extends boolean = false>(
  options: Options<ArchiveTasksRearchiveTaskData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    ArchiveTasksRearchiveTaskResponses,
    ArchiveTasksRearchiveTaskErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/archive-tasks/{task_id}/rearchive",
    ...options,
  });
};

/**
 * Resume Manual Action
 */
export const archiveTasksResumeManualAction = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ArchiveTasksResumeManualActionData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    ArchiveTasksResumeManualActionResponses,
    ArchiveTasksResumeManualActionErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/archive-tasks/{task_id}/resume-manual-action",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Continue Archive Video
 */
export const archiveTasksContinueArchiveVideo = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ArchiveTasksContinueArchiveVideoData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    ArchiveTasksContinueArchiveVideoResponses,
    ArchiveTasksContinueArchiveVideoErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/archive-tasks/{task_id}/continue-video",
    ...options,
  });
};

/**
 * Open Archive Task In Browser
 */
export const archiveTasksOpenArchiveTaskInBrowser = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ArchiveTasksOpenArchiveTaskInBrowserData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    ArchiveTasksOpenArchiveTaskInBrowserResponses,
    ArchiveTasksOpenArchiveTaskInBrowserErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/archive-tasks/{task_id}/open-browser",
    ...options,
  });
};

/**
 * Open Manual Action In Browser
 */
export const archiveTasksOpenManualActionInBrowser = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ArchiveTasksOpenManualActionInBrowserData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    ArchiveTasksOpenManualActionInBrowserResponses,
    ArchiveTasksOpenManualActionInBrowserErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/archive-tasks/{task_id}/manual-actions/{action_code}/open-browser",
    ...options,
  });
};

/**
 * Download Archive Result
 */
export const archiveTasksDownloadArchiveResult = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ArchiveTasksDownloadArchiveResultData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ArchiveTasksDownloadArchiveResultResponses,
    ArchiveTasksDownloadArchiveResultErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/archive-tasks/{task_id}/result",
    ...options,
  });
};

/**
 * View Archive Result
 */
export const archiveTasksViewArchiveResult = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ArchiveTasksViewArchiveResultData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ArchiveTasksViewArchiveResultResponses,
    ArchiveTasksViewArchiveResultErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/archive-tasks/{task_id}/result/view",
    ...options,
  });
};

/**
 * Download Video Result
 */
export const archiveTasksDownloadVideoResult = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ArchiveTasksDownloadVideoResultData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ArchiveTasksDownloadVideoResultResponses,
    ArchiveTasksDownloadVideoResultErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/archive-tasks/{task_id}/result/video",
    ...options,
  });
};

/**
 * List Rss Feeds
 */
export const rssFeedsListRssFeeds = <ThrowOnError extends boolean = false>(
  options?: Options<RssFeedsListRssFeedsData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    RssFeedsListRssFeedsResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/rss-feeds",
    ...options,
  });
};

/**
 * Create Rss Feed
 */
export const rssFeedsCreateRssFeed = <ThrowOnError extends boolean = false>(
  options: Options<RssFeedsCreateRssFeedData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    RssFeedsCreateRssFeedResponses,
    RssFeedsCreateRssFeedErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/rss-feeds",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete Rss Feed
 */
export const rssFeedsDeleteRssFeed = <ThrowOnError extends boolean = false>(
  options: Options<RssFeedsDeleteRssFeedData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    RssFeedsDeleteRssFeedResponses,
    RssFeedsDeleteRssFeedErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/rss-feeds/{feed_id}",
    ...options,
  });
};

/**
 * Update Rss Feed
 */
export const rssFeedsUpdateRssFeed = <ThrowOnError extends boolean = false>(
  options: Options<RssFeedsUpdateRssFeedData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    RssFeedsUpdateRssFeedResponses,
    RssFeedsUpdateRssFeedErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/rss-feeds/{feed_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Refresh Rss Feed
 */
export const rssFeedsRefreshRssFeed = <ThrowOnError extends boolean = false>(
  options: Options<RssFeedsRefreshRssFeedData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    RssFeedsRefreshRssFeedResponses,
    RssFeedsRefreshRssFeedErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/rss-feeds/{feed_id}/refresh",
    ...options,
  });
};

/**
 * Logout
 */
export const authLogout = <ThrowOnError extends boolean = false>(
  options?: Options<AuthLogoutData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).post<
    AuthLogoutResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/logout",
    ...options,
  });
};

/**
 * Read Current User
 */
export const authReadCurrentUser = <ThrowOnError extends boolean = false>(
  options?: Options<AuthReadCurrentUserData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    AuthReadCurrentUserResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/me",
    ...options,
  });
};
